---
dist: bionic  # Ubuntu 18.04
language: minimal

matrix:
  include:
    - name: Linter-Dockerfile (hadolint)
      language: minimal
      services:
        - docker
      before_install:
        - docker pull hadolint/hadolint
      script:
        - >
          docker run --rm -i
          -v ${PWD}/.conf/hadolint.yml:/root/.config/hadolint.yaml
          hadolint/hadolint
          < Dockerfile

    - name: Linter-YAML (yamllint)
      language: python
      python: 3.8
      before_install:
        - pip install yamllint
      script:
        - yamllint --config-file ./.conf/yamllint.yml .
